# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
#' @import RcppEigen
#' @title SNSMS for RCpp version
#' @description Self-normalized sequential change-point detection using RCpp
#' @param L a d-dimension object function
#' @param x a d-dimension time series data, expressed as a matrix
#' @param theta parameter estimates for the first m datas
#' @param m the number of observed data
#' @param alpha significance level
#' @param Tm the ratio of the monitoring horizon to the size of the training sample
#' @param d the dimension of data
#' @return a random sample of size \code{k}
#' @examples
#' \dontrun{
#'   L<-function(x,mu){(x-mu)^2}
#'   x<-matrix(c(rnorm(200,0,0.1),rnorm(1800,2,0.1)),nrow = 1)
#'   m<-180
#'   theta<-mean(x[1:m])
#'   alpha<-0.05
#'   Tm<-10
#'   d<-1
#'   k<-SNSMS_Cpp(L,x,theta,m,alpha,Tm,d)
#'   plot(x,type="l")
#'   abline(v=m+k,col="red")
#' }
#' @examples
#' \dontrun{
#'   library(MASS)
#'   L<-function(x,mu){(x-mu)^2}
#'   x<-cbind(t(mvrnorm(200,c(0,0),diag(c(1,1)))),t(mvrnorm(1800,c(1,2),diag(c(1,1)))))
#'   m<-180
#'   theta<-rowMeans(x[,1:m])
#'   alpha<-0.05
#'   Tm<-10
#'   d<-2
#'   k<-SNSMS_Cpp(L,x,theta,m,alpha,Tm,d)
#' }
#' @export
SNSMS_Cpp <- function(L, x, theta, m, alpha, Tm, d) {
    .Call('_SA23204161_SNSMS_Cpp', PACKAGE = 'SA23204161', L, x, theta, m, alpha, Tm, d)
}

